// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN033eQCTDxG_92xv-mzJy-d9N3-EWFtw',
    appId: '1:943198273238:web:2c4525037d1819edbb5377',
    messagingSenderId: '943198273238',
    projectId: 'camp-ride-system',
    authDomain: 'camp-ride-system.firebaseapp.com',
    databaseURL: 'https://camp-ride-system-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ride-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28cOCxf1oyAxktALWMK65hiSeFPJKcoM',
    appId: '1:943198273238:android:235cb3c6f1ac1bb1bb5377',
    messagingSenderId: '943198273238',
    projectId: 'camp-ride-system',
    databaseURL: 'https://camp-ride-system-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ride-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEi3ct8O6UroqaXCmvATXafg1Uq_qyKQU',
    appId: '1:943198273238:ios:e1fdd6c6ca5eae54bb5377',
    messagingSenderId: '943198273238',
    projectId: 'camp-ride-system',
    databaseURL: 'https://camp-ride-system-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ride-system.appspot.com',
    iosBundleId: 'com.driver.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEi3ct8O6UroqaXCmvATXafg1Uq_qyKQU',
    appId: '1:943198273238:ios:b1652f7ad52012c8bb5377',
    messagingSenderId: '943198273238',
    projectId: 'camp-ride-system',
    databaseURL: 'https://camp-ride-system-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ride-system.appspot.com',
    iosBundleId: 'com.example.campdriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN033eQCTDxG_92xv-mzJy-d9N3-EWFtw',
    appId: '1:943198273238:web:9581ca25a88d794dbb5377',
    messagingSenderId: '943198273238',
    projectId: 'camp-ride-system',
    authDomain: 'camp-ride-system.firebaseapp.com',
    databaseURL: 'https://camp-ride-system-default-rtdb.firebaseio.com',
    storageBucket: 'camp-ride-system.appspot.com',
  );

}